#!/bin/bash
workspaces() {

ws1="1"
ws2="2"
ws3="3"
ws4="4"
ws5="5"
ws6="6"

# Unoccupied
un="0"

# check if Occupied
# check if Focused

readarray response < <(hyprctl -j --batch 'activeworkspace; workspaces' | jq -s '.[0].id, .[1] | length')

active=${response[0]}
num_monitors=${response[1]}
echo "active id: ${active}"
echo "mon num: ${num_monitors}"
exit 0

ic_1=""
ic_2=""
ic_3=""
ic_4=""
ic_5=""
ic_6=""
if [ active_id -eq 1]; then
    ic_1=""
elif [ active_id -eq 2]; then
    ic_2=""
elif [ active_id -eq 3]; then
    ic_3=""
elif [ active_id -eq 4]; then
    ic_4=""
elif [ active_id -eq 5]; then
    ic_5=""
elif [ active_id -eq 6]; then
    ic_6=""
fi

echo 	"(box	:class \"works\"	:orientation \"h\" :spacing 5 :space-evenly \"false\" (button :onclick \"bspc desktop -f $ws1\"	:class	\"$un$o1$f1\"	\"$ic_1\") (button :onclick \"bspc desktop -f $ws2\"	:class \"$un$o2$f2\"	 \"$ic_2\") (button :onclick \"bspc desktop -f $ws3\"	:class \"$un$o3$f3\" \"$ic_3\") (button :onclick \"bspc desktop -f $ws4\"	:class \"$un$o4$f4\"	\"$ic_4\") (button :onclick \"bspc desktop -f $ws5\"	:class \"$un$o5$f5\" \"$ic_5\")  (button :onclick \"bspc desktop -f $ws6\"	:class \"$un$o6$f6\" \"$ic_6\"))"

}
workspaces
bspc subscribe desktop node_transfer | while read -r _ ; do
workspaces
done
